### ISSUE TITLE
Can't compile with 1.2 nightly

### ISSUE THREAD

**Issue by andrewrynhard** [thepowersgang/rust-barebones-kernel#6]
I know that 1.0 nightly is recommended but I wanted to try 1.2 nightly. Get the following:

```
x86_64-elf-ld -o ../kernel.amd64.bin -T arch/amd64/link.ld -Map .obj/amd64/map.txt --gc-sections -z max-page-size=0x1000 .obj/amd64/start.o .obj/amd64/kernel.o .obj/amd64/libcore.rlib
.obj/amd64/kernel.o: In function `fmt::Write::write_fmt::Adapter$LT$$u27$a$C$$u20$T$GT$.Write::write_fmt::h12553647585220172932':
main.0.rs:(.text._ZN3fmt5Write9write_fmt36Adapter$LT$$u27$a$C$$u20$T$GT$.Write9write_fmt21h12553647585220172932E+0x5a): undefined reference to `fmt::write::he06a9e58235fa9d6i5M'
.obj/amd64/kernel.o: In function `fmt::_$RF$$u27$a$u20$T.Display::fmt::h317396037922038184':
main.0.rs:(.text._ZN3fmt25_$RF$$u27$a$u20$T.Display3fmt19h317396037922038184E+0x1c): undefined reference to `fmt::str.Display::fmt::h2af2fe2576bb6edfMGN'
.obj/amd64/kernel.o: In function `kmain':
main.0.rs:(.text.kmain+0x127): undefined reference to `fmt::write::he06a9e58235fa9d6i5M'
main.0.rs:(.text.kmain+0x13c): undefined reference to `fmt::num::i32.fmt..Display::fmt::h3c80d6522088f321zaM'
main.0.rs:(.text.kmain+0x204): undefined reference to `fmt::write::he06a9e58235fa9d6i5M'
main.0.rs:(.text.kmain+0x2a9): undefined reference to `fmt::write::he06a9e58235fa9d6i5M'
main.0.rs:(.text.kmain+0x37d): undefined reference to `fmt::write::he06a9e58235fa9d6i5M'
main.0.rs:(.text.kmain+0x422): undefined reference to `fmt::write::he06a9e58235fa9d6i5M'
make: *** [../kernel.amd64.bin] Error 1
```

If I remove the calls to `log!` everything compiles and runs. New to Rust and would like to try and get this compiling with 1.2 as a way to start learning Rust. Any ideas?

**Comment by thepowersgang** [comment]
Interesting, works for me using latest nightly (`rustc 1.2.0-nightly (fbb13543f 2015-06-11)`). and binutils 2.22

**Comment by andrewrynhard** [comment]
Im using the same nightly, binutils 2.25.

**Comment by thepowersgang** [comment]
Fresh checkout (or effectively fresh?)

**Comment by thepowersgang** [comment]
Checked on both a 32-bit and 64-bit host with binutils 2.25. Not sure what problems you're having. (Feel free to join IRC for interactive help)

**Comment by justinas** [comment]
Having this same problem with my own kernel. Could you tell me which nightly you're using to build?

**Comment by thepowersgang** [comment]
Latest nightly (I will update the readme to reflect that it targets usually latest nightly) hits the SSE regisier return issue (rust-lang/rust#26449), and also has other compile errors caused by the recent splitting of the 'core' feature flag.

**Comment by Tyler-Hardin** [comment]
Any clues on a workaround for this @thepowersgang? I've even tried just enabling MMX, SSE, and SSE2 in the target file (if I don't hit the FP-using codepath, it won't #UD anyway.), and I still get some assert error from the C++ code in rustc.

The assert error, in case you're interested.

```
rustc -O --cfg arch__amd64 --target=arch/amd64/target.json -o .obj/amd64/libcore.rlib --crate-type=lib --emit=link,dep-info ../libcore/lib.rs
warning: ignoring specified output filename because multiple outputs were requested
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/MC/SubtargetFeature.cpp:197: llvm::FeatureBitset llvm::SubtargetFeatures::ApplyFeatureFlag(llvm::FeatureBitset, llvm::StringRef, llvm::ArrayRef<llvm::SubtargetFeatureKV>): Assertion `hasFlag(Feature)' failed.
Makefile:61: recipe for target '.obj/amd64/libcore.rlib' failed
make: *** [.obj/amd64/libcore.rlib] Aborted
```

**Comment by Tyler-Hardin** [comment]
Also, I saw you're discussion on rustc's bugtracker about this. I tried downgrading to LLVM 3.3 and it didn't fix the bug.

**Comment by thepowersgang** [comment]
The workaround I'm actively using for my kernel is patching libcore to disable all floating-point support.

Until there's a LLVM fix, or  an official patch for libcore, I'm not sure of the fix. (Also, just enabling SSE etc won't make it work, as that also enables the vectorized memcpy/memset)

**Comment by Tyler-Hardin** [comment]
Thanks for the quick reply. I checked out a commit from July 2nd that was compatible with your patch (master is no longer compatible), applied the patch, then ran `make` and I get:

```
rustc -O --cfg arch__amd64 --target=arch/amd64/target.json -o .obj/amd64/libcore.rlib --crate-name=core --crate-type=lib --emit=link,dep-info ../libcore/lib.rs
warning: ignoring specified output filename because multiple outputs were requested
../libcore/lib.rs:1:1: 1:1 error: can't find crate for `core`
../libcore/lib.rs:1 // Copyright 2014 The Rust Project Developers. See the COPYRIGHT
                    ^
error: aborting due to previous error
Makefile:61: recipe for target '.obj/amd64/libcore.rlib' failed
make: *** [.obj/amd64/libcore.rlib] Error 101
```

This has been an absolute nightmare trying to get rust working for osdev. I've setup g++ with working exceptions with less frustration than this. It's insane. (Not that I'm blaming you for that. You've done nothing but help with creating this barebones and trying to work around rust's lack of concern for this part of their userbase. I'm just venting.)

**Comment by thepowersgang** [comment]
I've just added the correct patch to the repo (which is for 1.4.0 libcore). With the latest nightlies, no_std loads core instead of std, so core's souce needs changing

**Comment by thepowersgang** [comment]
Closing due to being very outdated. Travis.ci builds are working, so I assume this is no longer an issue.
